{% set name = "devpi-common" %}
{% set version = "3.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/devpi-common-{{ version }}.tar.gz
  sha256: 6382d25a8eac6c79f6dfda927508f07d93b8732372a061505551af65b46061f4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.3
  run:
    - lazy
    - packaging
    - py >=1.4.20
    - python >=3.3
    - requests >=2.3.0

test:
  imports:
    - devpi_common
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/devpi/devpi
  dev_url: https://github.com/devpi/devpi/tree/main/common
  doc_url: http://doc.devpi.net/
  summary: Devpi utilities jointly used by devpi-server and devpi-client
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
